services:
  pb:
    build:
      context: pb/
    environment:
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
    volumes:
     - db-data:/pb/pb_data
     - ./pb/pb_migrations:/pb/pb_migrations:ro
     - ./pb/pb_hooks:/pb/pb_hooks:ro
    ports:
      - "3002:8090"
    working_dir: /app/pb
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8090/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - the-network

volumes:
  db-data:

networks:
  the-network:
