services:
  pb:
    build:
      context: pb/
    volumes:
     - db-data:/pb/pb_data
     - ./pb/pb_migrations:/pb/pb_migrations:ro
    ports:
      - "3002:8090"
    working_dir: /app/pb
    networks:
      - the-network
  
  grafana:
    image: grafana/grafana-oss
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
      # GF_SERVER_ROOT_URL: http://%(domain)s/grafana/
      GF_SECURITY_ALLOW_EMBEDDING: true
    ports:
     - "3001:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
     - db-data:/data_from_pb_service
    networks:
      - the-network

volumes:
  db-data:
  grafana-storage:

networks:
  the-network: